### ISSUE TITLE
transformers 0.4.x dependency

### ISSUE THREAD

**Issue by peti** [avieth/smtp-mail-ng#1]
Would you consider using `transformers-compat` to make this library buildable with any version of transformers? The 0.4.x version that you currently require is not available to users of GHC 7.8.4, because the compiler ships version 0.3.x as a core library that cannot be updated.

**Comment by avieth** [comment]
Got a patch in #2 . Could you pull it and let me know if it fixes the problem?

**Comment by avieth** [comment]
Resolved in #2
